# Generated by Django 4.0.5 on 2022-06-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_post_author_alter_post_preview_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(max_length=90),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_photo',
            field=models.ImageField(default='Screenshot_from_2022-06-21_16-39-23.png', upload_to='static/images/post_preview'),
        ),
    ]
