# Generated by Django 4.0.5 on 2022-06-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, default='test_email@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_photo',
            field=models.ImageField(default='Screenshot_from_2022-06-20_23-27-28.png', upload_to='static/images/post_preview'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='yehor.jpg', upload_to='static/images/user_profiles_jpg'),
        ),
    ]
