# Generated by Django 4.0.5 on 2022-06-30 22:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_email_alter_post_preview_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_path',
            field=blog.models.NameField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_photo',
            field=models.ImageField(default='Screenshot_from_2022-06-21_16-39-23.png', upload_to='static/images/post_preview'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='Screenshot_from_2022-06-22_03-57-39.png', upload_to='static/images/user_profiles_jpg'),
        ),
    ]
