# Generated by Django 4.0.5 on 2022-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_url_path_alter_post_preview_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_photo',
            field=models.ImageField(default='Screenshot_from_2022-06-20_23-27-28.png', upload_to='static/images/post_preview'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='andrii.jpg', upload_to='static/images/user_profiles_jpg'),
        ),
    ]
